=== XHighIntell/jintellv3/docs/schema/article-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://jintellv3.xhighintell.com/article/schema",
    "title": "The JSON schema for the article documents file",
    
    "definitions": {
        "name": {
            "type": [ "string", "array" ],
            "items": { "type": "string" }
        },
        "type": {
            "oneOf": [
                { "type": "string" },
                {
                    "type": "object",
                    "properties": {
                        "name": { "type": "string" },
                        "href": { "type": "string" }
                    },
                    "required": [ "name" ]
                }
            ]
        },
        "property": {
            "type": "object",
            "properties": {
                "name": { "$ref": "#/definitions/name" },
                "type": { "$ref": "#/definitions/type" },
                "description": { "$ref": "#/definitions/name" },
                "remarks": { "$ref": "#/definitions/name" }
            }
        },
        "method": {
            "type": "object",
            "properties": {
                "name": {
                    "allOf": [ { "$ref": "#/definitions/name" } ],
                    "description": "The title of the method.\n\nIt may use TypeScript syntax for clarity, e.g. 'add(menu: Menu): void'."
                },
                "description": {
                    "allOf": [ { "$ref": "#/definitions/name" } ],
                    "description": "The description of method."
                },

                "overloads": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/method" }
                },
                "parameters": { 
                    "type": "array",
                    "items": { "$ref": "#/definitions/property" }
                },
                "returns": {
                    "oneOf": [
                        { "$ref": "#/definitions/name" },
                        {
                            "type": "object",
                            "properties": {
                                "type": { "$ref": "#/definitions/type"},
                                "description": { "$ref": "#/definitions/name" }
                            }
                        }
                    ]
                },
                "remarks": { "$ref": "#/definitions/name" }
            },
            "required": [ "name", "description" ]
        }
    },

    "type": "object",
    "properties": {
        "kind": {
            "type": "string",
            "description": "The kind of document.",
            "enum": [ "method", "class", "interface", "field" ]
        },
        "title": {
            "type": "string",
            "description": "The title of the document."
        },
        "description": {
            "type": "string",
            "description": "The description of the document shown below the name."
        },

        "constructors": {
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },
        "properties": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "fields": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "events": {
            "type": "array",
            "items": {
                "properties": {
                    "name": { "type": "string" },
                    "bubbles": { "type": "boolean" },
                    "cancelable": { "type": "boolean" },
                    "description": { "type": "string" },
                    "properties": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/property" }
                    },
                    "fields": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/property" }
                    }
                }
            }
        },
        "methods": { 
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },

        "static_fields": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "static_methods": {
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },

        "examples": { "$ref": "#/definitions/name" },
        "after":  { "$ref": "#/definitions/name" }
    }
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/ComboBox/ComboBoxOption.json
{
    "kind": "class",
    "title": "ComboBoxOption Class",
    "description": "Represents a new option within the ComboBox.",
    
    "constructors": [
        {
            "name": "constructor(element?: HTMLElement)", 
            "description": "Initializes a new ComboBoxOption.", 
            "parameters": [
                {
                    "name": "element", 
                    "type": "HTMLElement",
                    "description": "The element for which to create ComboBoxOption control."
                }
            ]
        }
    ],

    "properties": [
        { "name": "readonly element: HTMLElement", "type": "HTMLElement", "description": "Gets the root element of the option." },
        { "name": "readonly elementIcon: HTMLElement", "type": "HTMLElement", "description": "Gets the Icon element of the option." },
        { "name": "readonly elementText: HTMLElement", "type": "HTMLElement", "description": "Gets the Text element of the option." },
        { 
            "name": "readonly parent?: ComboBox", 
            "type": { "name": "ComboBox", "href": "?q=intell.ctrl.ComboBox" },
            "description": "Gets the container element for search input." },
        {
            "name": "readonly group?: ComboBoxGroup",
            "type": { "name": "ComboBoxGroup", "href": "?q=intell.ctrl.ComboBoxGroup" },
            "description": "Gets the parent group of the option."
        },
        { 
            "name": "disabled: boolean", "type": "boolean", 
            "description": "Gets or sets a value indicating whether interaction with the option is disabled.",
            "remarks": [
                "<p>The default value is <mark>false</mark>.</p>",
                "<p>If disabled, the option will not respond to mouse clicks or keyboard selection. However, programmatic selection via code is still allowed.</p>"
            ]
        },
        { "name": "selected: boolean", "type": "boolean", "description": "Gets or sets whether the option is selected or not." },
        { 
            "name": "outline: boolean", "type": "boolean", 
            "description": "Gets or sets the outline visibility of the option. This value has no effect if the option does not have a parent." ,
            "remarks": "Only one option may be outlined at any given time."
        },
        { 
            "name": "hidden: boolean", "type": "boolean",
            "description": "Gets or sets whether the option is hidden.",
            "remarks": "If all options within a group are hidden, the group's visibility will be toggled to hidden as well."
        },
        { "name": "value: T", "type": "T", "description": "Gets the assigned value of the option." },
        { 
            "name": "icon?: string", "type": "string", "description": "Gets or sets the icon of the Option.",
            "remarks": "The icon can be an image URL (http:\/\/) or a CSS class (class:\/\/)."
        },
        { "name": "text: string", "type": "string", "description": "Gets or sets the display text of the option." },
        { "name": "description: string", "type": "string", "description": "Gets or sets the display description of the option." }

    ],

    "methods": [
        {
            "name": "remove(): void", 
            "description": "Removes the option from its parent. If it has no parent, calling <mark>remove()</mark> does nothing."
        },
        {
            "name": "matchKeywords(keywords: string[]): boolean",
            "description": "Checks whether the option matches all specified keywords.",
            "parameters": [
                {
                    "name": "keywords", "type": "string[]",
                    "description": "The array of keywords to match against."    
                }
            ],
            "returns": "Returns <mark>true</mark> if the option matches all specified keywords; otherwise, <mark>false</mark>."
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/TargetPopup/TargetPopup.json
{
    "kind": "class",
    "title": "TargetPopup Class",
    "description": "Represents a container that can be displayed anywhere or attached to another element.",

    "constructors": [
        {
            "name": "constructor(element?: HTMLElement)",
            "description": "Initializes a new instance of the TargetPopup class from element.",
            "parameters": [
                {
                    "name": "element",
                    "type": "HTMLElement",
                    "description": "The element for which to create TargetPopup control."
                }
            ]
        }
    ],

    "properties": [
        {
            "name": "readonly element: HTMLElement",
            "type": "HTMLElement",
            "description": "Gets the root element of the control."
        },
        {
            "name": "readonly elementAttached?: HTMLElement",
            "type": "HTMLElement | undefined",
            "description": "Gets the element attached to the TargetPopup.",
            "remarks": "If the TargetPopup is attached to an element, the <mark>POPUP-ATTACHED</mark> class is added to that element."
        },
        {
            "name": "readonly visible: boolean",
            "type": "boolean",
            "description": "Gets a value indicating whether the popup is displayed."
        },


        {
            "name": "locations: number[]",
            "type": "number[]",
            "description": "Gets or sets the placement locations for the popup.",
            "remarks": "The default value is <mark>[4, 12]</mark>."
        },
        {
            "name": "option: ShowAtOption",
            "type": {
                "name": "ShowAtOption",
                "href": "?q=intell.math.ShowAtOption"
            },
            "description": "Gets or sets the placement option for the popup.",
            "remarks": "The default value is <mark>{ distance: 0 }</mark>."
        }
    ],

    "methods": [
        {
            "name": "showAt",
            "description": "Shows the popup.",
            "overloads": [
                {
                    "name": "showAt(target: HTMLElement): void",
                    "description": "Shows the popup so that it stays near another element."
                },
                {
                    "name": "showAt(target: PointLike): void",
                    "description": "Shows the popup at the coordinates relative to the document."
                }
            ],
            "remarks": "The <mark>showAt</mark> method uses <a href='?q=intell.ctrl.showAt'><mark>intell.ctrl.showAt</mark></a> for positioning."
        },
        {
            "name": "hide",
            "description": "Hides the popup."
        }
    ],

    "events": [
        {
            "name": "targetpopuphide", "bubbles": true, "cancelable": false,
            "description": "The hiding event fires when the popup is hidden."
        }
    ],

    "static_methods": [
        {
            "name": "showAt(element: HTMLElement, target: HTMLElement, locations?: number[], option?: math.ShowAtOption): TargetPopup",
            "description": "Shows the specified element as the TargetPopup.",
            "overloads": [
                {
                    "name": "showAt(element: HTMLElement, target: HTMLElement, locations?: number[], option?: math.ShowAtOption): TargetPopup",
                    "description": "Shows the popup so that it stays near another element."
                },
                {
                    "name": "showAt(element: HTMLElement, target: PointLike, locations?: number[], option?: math.ShowAtOption): TargetPopup",
                    "description": "Shows the popup at the coordinates relative to the document."
                }
            ],
            "returns": "Returns the created <mark>TargetPopup</mark>.",
            "remarks": "The <mark>showAt</mark> instantiates a new TargetPopup or reuses; sets its location and options, and then calls <mark>TargetPopup.showAt</mark>."
        }
    ],

    "examples": "<a href=\"?q=intell.ctrl.TargetPopup-demo\">Click here</a> for more examples."
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/TimeSpan/TimeSpanFormatOption.json
{
    "kind": "interface",
    "title": "TimeSpanFormatOption Interface",
    "description": "Represents the options for parsing the timespan value.",
    
    
    "fields": [
        { "name": "strictness: number", "type": "number", 
            "description": "Gets or sets the strictness level for parsing the input text value.",
            "remarks": [
                "The default value is <mark>0</mark>.",
                "<p>When strictness equal 0, the <mark>/^(-?((\\d*\\.)?\\d+)(d|h|m|s|(ms)) *)*$/</mark> will be used.</p>",
                "<p>When strictness equal 1, the <mark>/^(-?(\\d*\\.)?\\d+d)? *(-?(\\d*\\.)?\\d+h)? *(-?(\\d*\\.)?\\d+m)? *(-?(\\d*\\.)?\\d+s)? *(-?(\\d*\\.)?\\d+ms)?$/</mark> will be used.</p>"
            ]
        },
        { "name": "decimalSeparator: string", "type": "string",
            "description": " Gets or sets the decimal separator character.",
            "remarks": "The default value is the locale’s decimal separator."
        },
        { "name": "thousandSeparator: string", "type": "string", 
            "description": "Gets or sets the thousand separator character",
            "remarks": "The default value is the locale’s thousand separator."
        }
    ]

}

=== XHighIntell/jintellv3/docs/article/globalThis/HTMLElement.json
{
    "kind": "method",
    "title": "HTMLElement.prototype",
    "description": "Useful built-in extensions for the <mark>HTMLElement</mark> prototype.",

    "methods": [
        {
            "name": "function getBoundingClientRectOffset(): DOMRect",
            "description": "Gets a DOMRect object that describes the element’s size and its position relative (including borders) to the document rather than the viewport.",
            "returns": {
                "type": { "name": "DOMRect" },
                "description": "Returns a DOMRect object."
            }
        },
        {
            "name": "function getBoundingClientContentRectOffset(): DOMRect",
            "description": "Gets a DOMRect object that describes the element’s size and its content position (excluding borders) relative to the document rather than the viewport.",
            "returns": {
                "type": { "name": "DOMRect" },
                "description": "Returns a DOMRect object."
            }
        },
        {
            "name": "function setOffset(offset: intell.math.PointLike): void",
            "description": "Sets the current coordinates of the element relative to the document.",
            "parameters": [
                {
                    "name": "offset",
                    "type": "intell.math.PointLike",
                    "description": "The new coordinates offset."
                }
            ]
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/ComboBox/ComboBoxGroup.json
{
    "kind": "class",
    "title": "ComboBoxGroup Class",
    "description": "Represents a ComboBoxGroup that contain a menu of options.",
    
    "constructors": [
        {
            "name": "constructor(element?: HTMLElement)", 
            "description": "Initializes a new ComboBoxGroup.", 
            "parameters": [
                {
                    "name": "element", 
                    "type": "HTMLElement",
                    "description": "The element for which to create ComboBoxGroup."
                }
            ]
        }
    ],

    "properties": [
        { "name": "readonly element: HTMLElement", "type": "HTMLElement", "description": "Gets the root element of this group." },
        { "name": "readonly elementHeader: HTMLElement", "type": "HTMLElement", "description": "Gets the element Header of this group.." },
        { "name": "readonly elementText: HTMLElement", "type": "HTMLElement", "description": "Gets the element Text of this group.." },
        { "name": "readonly elementChildren: HTMLElement", "type": "HTMLElement", "description": "Gets the element Children of this group." },
        { "name": "readonly focused: boolean", "type": "boolean", "description": "Gets a value indicating whether the control have input focus." },
        { "name": "readonly parent?: ComboBox", "type": { "name": "ComboBox", "href": "?q=intell.ctrl.ComboBox" }, "description": "Gets the parent ComboBox of this group." },
        { "name": "readonly options: ComboBoxOption[]", "type": "ComboBoxOption[]", "description": "Gets all options within this group." },

        { "name": "id?: string", "type": "string", "description": "Gets or sets the id of the group." },
        { "name": "text: string", "type": "string", "description": "Gets or sets the group's display text." },
        { 
            "name": "default: boolean", "type": "boolean", 
            "description": "Gets or sets whether this is the default group. Default groups do not display a header." 
        }
    ],

    "methods": [
        {
            "name": "add(item: ComboBoxOption): void", 
            "description": "Adds a new option to the end of the list for this group.",
        
            "parameters": [
                {
                    "name": "item",
                    "type": {"name": "ComboBoxOption", "href": "?q=intell.ctrl.ComboBoxOption" },
                    "description": "The new option to add."
                }
            ],
            "remarks": "This method removes the option from its current parent, if one exists, before adding it to the new group."
        },
        {
            "name": "remove(): void", "description": "Removes the group from its parent. If it has no parent, calling <mark>remove()</mark> does nothing." 
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/intell/wait.json
{
    "kind": "method",
    "title": "wait Function",
    "description": "Creates a promise that will resolve after a time delay.",

    "methods": [
        {
            "name": "function wait(delay: number): Promise&lt;void&gt;",
            "description": "",
            "parameters": [
                {
                    "name": "delay",
                    "type": "number",
                    "description": "The delay in milliseconds."
                }
            ],
            "returns": {
                "type": { "name": "Promise&lt;void&gt;" },
                "description": "Returns a promise that will resolve after a time delay."
            }
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/intell.math/ShowAtOption.json
{
    "kind": "interface",
    "title": "ShowAtOption Interface",
    "description": "The ShowAt option; this is used to calculate the placement position.",

    "fields": [
        { 
            "name": "container?: DOMRect",
            "type": "DOMRect" ,
            "description": "The rectangle within which the popup must be placed."
        },
        { 
            "name": "distance?: number",
            "type": "number" ,
            "description": "The minimum distance between the popup and the target."
        },
        { 
            "name": "distanceToContainer?: number",
            "type": "number" ,
            "description": "The minimum distance between the popup and the container."
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/globalThis/Element.json
{
    "kind": "method",
    "title": "Element.prototype",
    "description": "Useful built-in extensions for the <mark>Element</mark> prototype.",

    "methods": [
        {
            "name": "function appendTo(target: Element): this",
            "description": "Appends the element to the end of the target element.",
            "parameters": [
                {
                    "name": "target",
                    "type": "Element",
                    "description": "Appended to the end of the target element."
                }
            ],
            "returns": {
                "type": { "name": "this" },
                "description": "Returns the same element instance to allow for method chaining."
            }
        },
        {
            "name": "function prependTo(target: Element): this",
            "description": "Appends the element to the beginning of the target element.",
            "parameters": [
                {
                    "name": "target",
                    "type": "Element",
                    "description": "Appended to the beginning of the target element."
                }
            ],
            "returns": {
                "type": { "name": "this" },
                "description": "Returns the same element instance to allow for method chaining."
            }
        }
    ]
}
