=== XHighIntell/jintellv3/docs/schema/article-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://jintellv3.xhighintell.com/article/schema",
    "title": "The JSON schema for the article documents file",
    
    "definitions": {
        "name": {
            "type": [ "string", "array" ],
            "items": { "type": "string" }
        },
        "type": {
            "oneOf": [
                { "type": "string" },
                {
                    "type": "object",
                    "properties": {
                        "name": { "type": "string" },
                        "href": { "type": "string" }
                    },
                    "required": [ "name" ]
                }
            ]
        },
        "property": {
            "type": "object",
            "properties": {
                "name": { "$ref": "#/definitions/name" },
                "type": { "$ref": "#/definitions/type" },
                "description": { "$ref": "#/definitions/name" },
                "remarks": { "$ref": "#/definitions/name" }
            }
        },
        "method": {
            "type": "object",
            "properties": {
                "name": {
                    "allOf": [ { "$ref": "#/definitions/name" } ],
                    "description": "The title of the method.\n\nIt may use TypeScript syntax for clarity, e.g. 'add(menu: Menu): void'."
                },
                "description": {
                    "allOf": [ { "$ref": "#/definitions/name" } ],
                    "description": "The description of method."
                },

                "overloads": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/method" }
                },
                "parameters": { 
                    "type": "array",
                    "items": { "$ref": "#/definitions/property" }
                },
                "returns": {
                    "oneOf": [
                        { "$ref": "#/definitions/name" },
                        {
                            "type": "object",
                            "properties": {
                                "type": { "$ref": "#/definitions/type"},
                                "description": { "$ref": "#/definitions/name" }
                            }
                        }
                    ]
                },
                "remarks": { "$ref": "#/definitions/name" }
            },
            "required": [ "name", "description" ]
        }
    },

    "type": "object",
    "properties": {
        "kind": {
            "type": "string",
            "description": "The kind of document.",
            "enum": [ "method", "class", "interface", "field" ]
        },
        "title": {
            "type": "string",
            "description": "The title of the document."
        },
        "description": {
            "type": "string",
            "description": "The description of the document shown below the name."
        },

        "constructors": {
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },
        "properties": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "fields": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "events": {
            "type": "array",
            "items": {
                "properties": {
                    "name": { "type": "string" },
                    "bubbles": { "type": "boolean" },
                    "cancelable": { "type": "boolean" },
                    "description": { "type": "string" },
                    "properties": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/property" }
                    },
                    "fields": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/property" }
                    }
                }
            }
        },
        "methods": { 
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },

        "static_fields": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "static_methods": {
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },

        "examples": { "$ref": "#/definitions/name" },
        "after":  { "$ref": "#/definitions/name" }
    }
}

=== XHighIntell/jintellv3/docs/article/intell.portal/ApplicationManifest.json
{
    "kind": "interface",
    "title": "ApplicationManifest Interface",
    "description": "The manifest of application.",
    

    "fields": [
        { "name": "id: string", "type": "string", "description": "A unique identifier for the application." },
        { "name": "name: string", "type": "string", "description": "The application's name." },
        { "name": "description: string", "type": "string", "description": "A plain text string (no HTML or other formatting) that describes the application while loading." },
        { "name": "title?: string", "type": "string", "description": "A short tooltip title of the application." },
        { "name": "icon?: string", "type": "string", "description": "The application icon. This can be a URL or an icon class (using the <mark>class:\/\/</mark> prefix)." },
        { "name": "shortcut?: boolean", "type": "string", "description": "Pins this application to menu. The default is true." },
        { "name": "group?: string", "type": "string", "description": "The shortcut group name." },
        { "name": "startup?: boolean", "type": "string", "description": "Sets whether the application should run on startup. The default is false." },
        {
            "name": "content: ApplicationManifestContent",
            "type": {
                "name": "ApplicationManifestContent",
                "href": "?q=intell.portal.ApplicationManifestContent"
            },
            "description": "The content of the application."
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/intell.portal/Application.json
{
    "kind": "class",
    "title": "Application Class",
    "description": "Represents an portal application.",
    
    "constructors": [
        {
            "name": "constructor(manifest: ApplicationManifest)", 
            "description": "Initializes a new instance of the Application class from manifest.", 
            "parameters": [
                {
                    "name": "manifest", 
                    "type": { "name": "ApplicationManifest", "href": "?q=intell.portal.ApplicationManifest" },
                    "description": "The manifest used to create the application."
                }
            ]
        }
    ],

    "properties": [
        { "name": "readonly manifest: ApplicationManifest", "type": { "name": "ApplicationManifest", "href": "?q=intell.portal.ApplicationManifest" }, "description": "Gets the status of the application." },
        { "name": "readonly status: string", "type": "string", "description": "Gets the status of the application.", "remarks": "The application status can be <mark>NONE</mark>, <mark>LOADING</mark>, <mark>LOADED</mark>, or <mark>FAILED</mark>." },
        { "name": "readonly shortcut: TaskbarShortcut", "type": "TaskbarShortcut", "description": "Gets the Taskbar shortcut of the application." },
        { 
            "name": "readonly portal?: Portal", 
            "type": { "name": "Portal", "href": "?q=intell.portal.Portal" },
            "description": "Gets the portal of the application.",
            "remarks": "The value is <mark>null</mark> if the application hasn't been added to the portal."
        },
        { 
            "name": "readonly elementRoot?: HTMLElement", "type": "HTMLElement",
            "description": "Gets the the root content element of the application.",
            "remarks": "The value is <mark>null</mark> if the application hasn't finished loading its HTML content."
        },
        { "name": "readonly error?: Error", "type": "Error", "description": "Gets the error that occurred while loading the application." }
    ],

    "methods": [
        {
            "name": "load(): Promise&lt;void&gt;",
            "description": "Loads the application. Subsequent calls return the previous Promise."
        },
        {
            "name": "addPostInitTask(init: (this: Application) => Promise&lt;any&gt; | any)", 
            "description": "Adds a post-initialization task to the application that executes after it loads.",
            "parameters": [
                {
                    "name": "init",  "type": "Function",
                    "description": "The post-initialization task function."
                }
            ],
            "remarks": "The post-initialization task can return a Promise for long-running jobs. The portal overlay will display a loading page until the task finishes."
        }
    ]
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/TimeSpan/TimeSpan.json
{
    "kind": "class",
    "title": "TimeSpan Class",
    "description": "Represents a control that displays a timespan or duration value.",
    
    "constructors": [
        {
            "name": "constructor(element?: HTMLElement)", 
            "description": "Initializes a new instance of the TimeSpan class from element.", 
            "parameters": [
                {
                    "name": "element", 
                    "type": "HTMLElement",
                    "description": "The element for which to create TimeSpan control."
                }
            ]
        }
    ],

    "properties": [
        { "name": "readonly element: HTMLElement", "type": "HTMLElement", "description": "Gets the root element of the control." },
        { "name": "readonly elementInput: HTMLElement", "type": "HTMLElement", "description": "Gets the input element of the control." },
        { "name": "readonly focused: boolean", "type": "boolean", "description": "Gets a value indicating whether the control have input focus." },

        
        { "name": "value?: number", "type": "number", 
            "description": "Gets or sets the value in milliseconds.", 
            "remarks": "The default value is <mark>null</mark>." 
        },
        { "name": "min?: number", "type": "number", 
            "description": "Gets or sets the minimum allowed value.",
            "remarks": "The default value is <mark>null</mark>."
        },
        { "name": "max?: number", "type": "number",
            "description": "Gets or sets the maxium allowed value.",
            "remarks": "The default value is <mark>null</mark>."
        },
        { "name": "step: number", "type": "number", 
            "description": "Gets or sets the amount to increment or decrement when the up or down arrow keys are pressed.",
            "remarks": "The default value is <mark>60000</mark>."
        },

        { "name": "stepViaWheel: boolean", "type": "boolean", 
            "description": "Gets or sets a value indicating whether the control can accept step changes via the mouse wheel.",
            "remarks": "The default value is <mark>false</mark>." 
        },
        { "name": "strictness: number", "type": "number", 
            "description": "Gets or sets the strictness level for parsing the input text value.",
            "remarks": [
                "The default value is <mark>0</mark>.",
                "<p>When strictness equal 0, the <mark>/^(-?((\\d*\\.)?\\d+)(d|h|m|s|(ms)) *)*$/</mark> will be used.</p>",
                "<p>When strictness equal 1, the <mark>/^(-?(\\d*\\.)?\\d+d)? *(-?(\\d*\\.)?\\d+h)? *(-?(\\d*\\.)?\\d+m)? *(-?(\\d*\\.)?\\d+s)? *(-?(\\d*\\.)?\\d+ms)?$/</mark> will be used.</p>"
            ]
        },
        { "name": "decimalSeparator: string", "type": "string",
            "description": " Gets or sets the decimal separator character.",
            "remarks": "The default value is the locale’s decimal separator."
        },
        { "name": "thousandSeparator: string", "type": "string", 
            "description": "Gets or sets the thousand separator character",
            "remarks": "The default value is the locale’s thousand separator."
        },
        { "name": "nullable: boolean", "type": "boolean", 
            "description": "Gets or sets whether the value can be null.",
            "remarks": "The default value is <mark>true</mark>."
        },
        { "name": "readonly: boolean", "type": "boolean", 
            "description": "Gets or sets whether the control is not mutable, meaning the user can not edit the control.",
            "remarks": "The default value is <mark>false</mark>."
        }
    ],

    "methods": [],

    "events": [
        {
            "name": "timespanchange", "bubbles": true, "cancelable": false,
            "description": "The change event is fired when the user modifies and commits the value."
        }
    ],

    "static_fields": [

    ],
    "static_methods": [
        {
            "name": "isValid", "description": "Checks whether the timespan text is valid.",
            "parameters": [
                {
                    "name": "text",
                    "type": "string",
                    "description": "The input string to be checked." 
                },
                {
                    "name": "option",
                    "type": {"name": "TimeSpanFormatOption", "href": "?q=intell.ctrl.TimeSpanFormatOption"},
                    "description": "The options for parsing the value."
                }
            ],
            "returns": {
                "type": "boolean",
                "description": "<p>Returns <mark>false</mark> if the timespan text is invalid.</p>"
            }
        },
        {
            "name": "parse", "description": "Returns a floating-point number representing milliseconds, parsed from the given string specified language-sensitive representation.",
            "parameters": [
                {
                    "name": "text",
                    "type": "string",
                    "description": "The input string to be parsed." 
                },
                {
                    "name": "option",
                    "type": {"name": "TimeSpanFormatOption", "href": "?q=intell.ctrl.TimeSpanFormatOption"},
                    "description": "The options for parsing the value."
                }
            ],
            "returns": {
                "type": "number",
                "description": [
                    "<p>Returns the value in milliseconds.</p>",
                    "<p>Returns <mark>NaN</mark> if the timespan text is invalid.</p>"
                ]
            },
            "remarks": "This method calls <mark>isValid</mark> before parsing. If <mark>isValid</mark> returns <mark>false</mark>, the method returns <mark>NaN</mark>."
        },
        {
            "name": "format", "description": "Formats a timespan value into an array of Nodes representing the timespan.",
            "parameters": [
                {
                    "name": "value",
                    "type": "number",
                    "description": "The timespan value to be formated." 
                },
                {
                    "name": "option",
                    "type": {"name": "TimeSpanFormatOption", "href": "?q=intell.ctrl.TimeSpanFormatOption"},
                    "description": "The options for formating the value."
                }
            ],
            "returns": {
                "type": "Node[]",
                "description": [
                    "<p>Returns the value in milliseconds.</p>",
                    "<p>Returns <mark>NaN</mark> if the timespan text is invalid.</p>"
                ]
            },
            "remarks": "If value is <mark>null</mark> or <mark>NaN</mark>, return empty array."
        }
    ],

    "examples": "<a href=\"?q=intell.ctrl.TimeSpan-demo\">Click here</a> for more examples."
}

=== XHighIntell/jintellv3/docs/article/intell/qs.json
{
    "kind": "method",
    "title": "qs Function",
    "description": "Create a query object from a string.",

    "methods": [
        {
            "name": "function qs(search?: string): { [T: string]: string }",
            "description": "Create a query object from a string.",
            "parameters": [
                {
                    "name": "search",
                    "type": "string[]",
                    "description": "The string containing key value pair that separate by <mark>=</mark>. <br>If <mark>search</mark> is not specified, <mark>location.search.substr(1)</mark> will be used instead."
                }
            ],
            "returns": "Return the key value pair object.", 
            "remarks": "this is remarks."
        }
    ],
    "examples": ""
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/Menu/MenuItem.json
{
    "kind": "class",
    "title": "MenuItem Class",
    "description": "Represents a MenuItem.",
    
    "constructors": [
        {
            "name": "constructor(element?: HTMLElement)", 
            "description": "Initializes a new MenuItem.", 
            "parameters": [
                {
                    "name": "element", 
                    "type": "HTMLElement",
                    "description": "The element for which to create MenuItem control."
                }
            ]
        }
    ],

    "properties": [
        { "name": "readonly element: HTMLElement", "type": "HTMLElement", "description": "Gets the root element of the item." },
        { "name": "readonly elementLabel: HTMLElement", "type": "HTMLElement", "description": "Gets the Label element of the item." },
        { "name": "readonly elementIcon: HTMLElement", "type": "HTMLElement", "description": "Gets the Icon element of the item." },
        { "name": "readonly elementText: HTMLElement", "type": "HTMLElement", "description": "Gets the Text element of the item." },
        { "name": "readonly elementChildren: HTMLElement", "type": "HTMLElement", "description": "Gets the Children element of the item." },
        { 
            "name": "readonly parent?: Menu | MenuItem", 
            "type": { "name": "Menu | MenuItem" },
            "description": "Gets the parent Menu or MenuItem that the item belongs to." 
        },
        {
            "name": "readonly children: MenuItem[]",
            "type": { "name": "MenuItem[]", "href": "?q=intell.ctrl.MenuItem" },
            "description": "Gets the child menu items."
        },
        { 
            "name": "readonly childrenVisible: boolean", "type": "boolean", 
            "description": "Gets a value indicating whether the dropdown children are displayed."
        },

        { 
            "name": "active: boolean", "type": "boolean", 
            "description": "Gets or sets whether the menu is actived or not. ",
            "remarks": [
                "<p>The default value is <mark>false</mark>.</p>",
                "<p>When the MenuItem is deactivated, its children are automatically hidden.</p>",
                "<p>When the MenuItem is activated, the visibility of its children remains unchanged.</p>"
            ]
        },
        { 
            "name": "disabled: boolean", "type": "boolean", 
            "description": "Gets or sets a value indicating whether interaction with the option is disabled. If disabled, the option will not respond to mouse clicks or keyboard selection.",
            "remarks": "<p>The default value is <mark>false</mark>.</p>"
        },

        { 
            "name": "childrenLocations?: number[]", "type": "number[]",
            "description": "Gets or sets the placement locations for the dropdowns",
            "remarks": "<p>The default value is <mark>undefined</mark>.</p>"
        },
        { 
            "name": "childrenOption?: ShowAtOption", "type": { "name": "ShowAtOption", "href": "?q=intell.ctrl.ShowAtOption" }, 
            "description": "Gets or sets the placement option of the dropdowns.",
            "remarks": "<p>The default value is <mark>undefined</mark>.</p>"
        },
        { 
            "name": "childrenDirection?: string", "type": "\"row\" | \"column\"", 
            "description": "Gets or sets the input direction of children. This value does not determine the children layout; rather, it dictates how user input is handled.",
            "remarks": "<p>The default value is <mark>undefined</mark>.</p>"
        },
        { 
            "name": "childrenIntersectEnabled?: boolean", "type": "boolean", 
            "description": "Gets or sets a value indicating whether the intersection overlay is enabled.",
            "remarks": "<p>The default value is <mark>undefined</mark>.</p>"
        },

        { 
            "name": "icon?: string", "type": "string", "description": "Gets or sets the icon of the MenuItem.",
            "remarks": "The icon can be an image URL (http:\/\/) or a CSS class (class:\/\/)."
        },
        { "name": "text: string", "type": "string", "description": "Gets or sets the displaying text of the Text element." },
        { "name": "title: string", "type": "string", "description": "Gets or sets the title of the Label element ." }
    ],

    "methods": [
        {
            "name": "showChildren(delay?: number, force?: boolean)", 
            "description": "Shows the dropdown children.",
            "parameters": [
                {
                    "name": "delay", "type": "number", 
                    "description": "The visibility delay for child dropdowns. The default value is <mark>Menu.CHILDREN_VISIBLE_DELAY</mark>."
                },
                {
                    "name": "force", "type": "boolean",
                    "description": [
                        "<p>Forces the dropdown picker to reposition, even if it is already visible.This is useful for reflecting changes when childrenLocations, childrenOption are updated.</p>",
                        "The default value is <mark>false</mark>."
                    ]
                }
            ]
        },
        {
            "name": "hideChildren(delay?: number)", 
            "description": "Hides the dropdown children.",
            "parameters": [
                {
                    "name": "delay", "type": "number", 
                    "description": "The visibility delay for child dropdowns. The default value is <mark>Menu.CHILDREN_VISIBLE_DELAY</mark>."
                }
            ]
        },
        {
            "name": "toggleChildren(delay?: number, force?: boolean)", 
            "description": "Toggle shows/hides dropdown children.",
            "parameters": [
                {
                    "name": "delay", "type": "number", 
                    "description": "The visibility delay for child dropdowns. The default value is <mark>Menu.CHILDREN_VISIBLE_DELAY</mark>."
                },
                {
                    "name": "force", "type": "boolean",
                    "description": [
                        "<p>Forces the dropdown picker to reposition, even if it is already visible.This is useful for reflecting changes when childrenLocations, childrenOption are updated.</p>",
                        "The default value is <mark>false</mark>."
                    ]
                }
            ]
        },
        {
            "name": "add", 
            "description": "Adds a new menu item, a separator, or a tree of items to the menu item.",
            "overloads": [
                { 
                    "name": "add(modifiers: MenuItemAddModifiers | string): MenuItem", 
                    "description": "Adds a separator, or a tree of items to the menu.",
                    "parameters": [
                        {
                            "name": "modifiers", "type": { "name": "MenuItemAddModifiers", "href": "?q=intell.ctrl.MenuItemAddModifiers" },
                            "description": "The modifiers from which the menu item will be created."
                        }
                    ],
                    "returns": { 
                        "type": { "name": "MenuItem", "href": "?q=intell.ctrl.MenuItem" },
                        "description": "Returns the newly created MenuItem that was added to the menu."
                    },
                    "remarks": "If the parameter is '--', a separator will be added to the menu."
                },
                { 
                    "name": "add(item: MenuItem): void", 
                    "description": "Adds MenuItem into the menu.",
                    "parameters": [
                        {
                            "name": "item", "type": { "name": "MenuItem", "href": "?q=intell.ctrl.MenuItem" },
                            "description": "The MenuItem to be added to the menu."
                        }
                    ],
                    "remarks": "This method removes the menu from its current parent, if one exists, before adding it to the new parent."
                }
            ]

        },
        {
            "name": "remove(): void", 
            "description": "Removes the option from its parent. If it has no parent, calling <mark>remove()</mark> does nothing."
        },
        {
            "name": "getActiveItem(): MenuItem | undefined", 
            "description": "Gets the active child item in the menu.",
            "returns": "Returns <mark>undefined</mark> if no active menu exists."
        },
        {
            "name": "getDeepestActive(): MenuItem | undefined", 
            "description": "Gets the most deeply nested active menu in the menu tree.",
            "returns": "Returns <mark>undefined</mark> if no active menu exists."
        }
    ]
}
