=== XHighIntell/jintellv3/docs/schema/article-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://jintellv3.xhighintell.com/article/schema",
    "title": "The JSON schema for the article documents file",
    
    "definitions": {
        "name": {
            "type": [ "string", "array" ],
            "items": { "type": "string" }
        },
        "type": {
            "oneOf": [
                { "type": "string" },
                {
                    "type": "object",
                    "properties": {
                        "name": { "type": "string" },
                        "href": { "type": "string" }
                    },
                    "required": [ "name" ]
                }
            ]
        },
        "property": {
            "type": "object",
            "properties": {
                "name": { "$ref": "#/definitions/name" },
                "type": { "$ref": "#/definitions/type" },
                "description": { "$ref": "#/definitions/name" },
                "remarks": { "$ref": "#/definitions/name" }
            }
        },
        "method": {
            "type": "object",
            "properties": {
                "name": {
                    "allOf": [ { "$ref": "#/definitions/name" } ],
                    "description": "The title of the method.\n\nIt may use TypeScript syntax for clarity, e.g. 'add(menu: Menu): void'."
                },
                "description": {
                    "allOf": [ { "$ref": "#/definitions/name" } ],
                    "description": "The description of method."
                },

                "overloads": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/method" }
                },
                "parameters": { 
                    "type": "array",
                    "items": { "$ref": "#/definitions/property" }
                },
                "returns": {
                    "oneOf": [
                        { "$ref": "#/definitions/name" },
                        {
                            "type": "object",
                            "properties": {
                                "type": { "$ref": "#/definitions/type"},
                                "description": { "$ref": "#/definitions/name" }
                            }
                        }
                    ]
                },
                "remarks": { "$ref": "#/definitions/name" }
            },
            "required": [ "name", "description" ]
        }
    },

    "type": "object",
    "properties": {
        "kind": {
            "type": "string",
            "description": "The kind of document.",
            "enum": [ "method", "class", "interface", "field" ]
        },
        "title": {
            "type": "string",
            "description": "The title of the document."
        },
        "description": {
            "type": "string",
            "description": "The description of the document shown below the name."
        },

        "constructors": {
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },
        "properties": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "fields": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "events": {
            "type": "array",
            "items": {
                "properties": {
                    "name": { "type": "string" },
                    "bubbles": { "type": "boolean" },
                    "cancelable": { "type": "boolean" },
                    "description": { "type": "string" },
                    "properties": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/property" }
                    },
                    "fields": {
                        "type": "array",
                        "items": { "$ref": "#/definitions/property" }
                    }
                }
            }
        },
        "methods": { 
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },

        "static_fields": {
            "type": "array",
            "items": { "$ref": "#/definitions/property" }
        },
        "static_methods": {
            "type": "array",
            "items": { "$ref": "#/definitions/method" }
        },

        "examples": { "$ref": "#/definitions/name" },
        "after":  { "$ref": "#/definitions/name" }
    }
}

=== XHighIntell/jintellv3/docs/article/intell.ctrl/Numeric/Numeric.json
{
    "kind": "class",
    "title": "Numeric Class",
    "description": "Represents a spin box that displays numeric value.",
    
    "constructors": [
        {
            "name": "constructor(element?: HTMLElement)", 
            "description": "Initializes a new numeric box.", 
            "parameters": [
                {
                    "name": "element", 
                    "type": "HTMLElement",
                    "description": "The element for which to create Numeric control."
                }
            ]
        }
    ],

    "properties": [
        { "name": "readonly element: HTMLElement", "type": "HTMLElement", "description": "Gets the root element of the control." },
        { "name": "readonly elementPrefix: HTMLElement", "type": "HTMLElement", "description": "Gets the prefix element." },
        { "name": "readonly elementSuffix: HTMLElement", "type": "HTMLElement", "description": "Gets the suffix element." },
        { "name": "readonly elementInput: HTMLElement", "type": "HTMLElement", "description": "Gets the input element." },
        { "name": "readonly elementUp: HTMLElement", "type": "HTMLElement", "description": "Gets the button‑up element." },
        { "name": "readonly elementDown: HTMLElement", "type": "HTMLElement", "description": "Gets the button‑down element." },
        { "name": "readonly focused: boolean", "type": "boolean", "description": "Gets a value indicating whether the control have input focus." },

        { "name": "value?: number", "type": "number", "description": "Gets or sets the value of Numeric." },
        { "name": "min?: number", "type": "number", "description": "Gets or sets the minimum allowed value; the default is null." },
        { "name": "max?: number", "type": "number", "description": "Gets or sets the maxium allowed value; the default is null." },
        { 
            "name": "prefix: string", "type": "string",
            "description": "Gets or sets the prefix character. Default: <mark>\"\"</mark> (empty string).",
            "remarks": "If the Numeric has a valid prefix, <mark>HAS-PREFIX</mark> class is added to the element."
        },
        { 
            "name": "suffix: string", "type": "string", 
            "description": "Gets or sets the suffix character. Default: <mark>\"\"</mark> (empty string).",
            "remarks": "If the Numeric has a valid suffix, <mark>HAS-SUFFIX</mark> class is added to the element."
        },

        { "name": "step: number", "type": "number", "description": "Gets or sets the value to increment or decrement the spin box (also known as an up-down control) when the up or down buttons are clicked; the default is <mark>1</mark>." },
        { "name": "stepViaWheel: boolean", "type": "boolean", "description": "Gets or sets a value indicating whether the control can accept step changes via the mouse wheel; the default is <mark>false</mark>." },

        { "name": "minimumFractionDigits: number", "type": "number", "description": "Gets or sets the minimum number of digits to appear after the decimal point; the default is <mark>0</mark>." },
        { "name": "maximumFractionDigits: number", "type": "number", "description": "Gets or sets the maximum number of digits to appear after the decimal point; the default is <mark>2</mark>." },
        { "name": "decimalSeparator: string", "type": "string", "description": "Gets or sets the decimal separator character; the default value is the locale’s decimal separator." },
        { "name": "thousandSeparator: string", "type": "string", "description": "Gets or sets the thousand separator character; the default value is the locale’s thousand separator." },

        { "name": "nullable: boolean", "type": "boolean", "description": "Gets or sets whether the value can be null; the default is <mark>true</mark>." },
        { "name": "readonly: boolean", "type": "boolean", "description": "Gets or sets whether the control is not mutable, meaning the user can not edit the control; the default is <mark>false</mark>." },
        { "name": "controls: boolean", "type": "boolean", "description": "Gets or sets whether the increment and decrement buttons are visible; the default is <mark>false</mark>." }
    ],

    "events": [
        {
            "name": "numericchange", "bubbles": true, "cancelable": false,
            "description": "The change event is fired when the user modifies and commits the value."
        }
    ],

    "static_methods": [
        {
            "name": "parseFloat(text: string, option: NumericFormatOption): number", 
            "description": "Parses an argument, converting it to a string if necessary, and returns a floating-point number.",
        
            "parameters": [
                {
                    "name": "name",
                    "type": "string",
                    "description": "The value to parse. If it is not a string, it is converted to one using the ToString abstract operation."
                },
                {
                    "name": "option",
                    "type": {
                        "name": "NumericFormatOption",
                        "href": "?q=intell.ctrl.NumericFormatOption"
                    },
                    "description": "An object that supplies culture-specific formatting information."
                }
            ],
             "returns": {
                 "type": "number",
                 "description": "Returns a floating-point number parsed from the given string using the specified language-sensitive representation."
             }
        },
        {
            "name": "formatNumber(number?: number, option: NumericFormatOption): string",
            "description": "Format a number argument.",
            "parameters": [
                {
                    "name": "number",
                    "type": "string",
                    "description": "The number to format."
                },
                {
                    "name": "option",
                    "type": {
                        "name": "NumericFormatOption",
                        "href": "?q=intell.ctrl.NumericFormatOption"
                    },
                    "description": "An object that supplies culture-specific formatting information."
                }
            ],
            "remarks": [
                "The runtime's default locale is used if both <mark>option.thousandSeparator</mark> and <mark>option.decimalSeparator</mark> is undefined. ",
                "If only one of the options is defined, the undefined option falls back to an empty string."
            ],
            "returns": {
                "type": "string",
                "description": "Returns a language-sensitive string representation of the given floating-point number."
            }
        }
    ],

    "examples": ["<div><a href=\"?q=intell.ctrl.Numeric-demo\">Click here</a> for more examples.</div>"]
}
